import { IsNotEmpty, IsString, IsOptional, IsJSON } from 'class-validator';

export class CreateTenantDto {
  @IsString()
  @IsNotEmpty()
  name!: string;

  @IsString()
  @IsOptional() // Subdomain is now optional from the client, as it will be generated by the service.
  subdomain?: string;

  @IsOptional()
  @IsJSON()
  settings?: string;
}